Fixup
Signed-off-by: Paul Chaignon <paul.chaignon@gmail.com>

diff --git a/.github/workflows/llvm-to-smt.yml b/.github/workflows/llvm-to-smt.yml
--- a/.github/workflows/llvm-to-smt.yml
+++ b/.github/workflows/llvm-to-smt.yml
@@ -37,7 +37,8 @@ jobs:
           echo $?
           whereis clang
           clang --version
-          ls -l /usr/bin/clang*
+          ls -l /usr/bin/clang
+          ls -l /etc/alternatives/clang*
       - name: Install Python dependencies
         run: |
           pip install -r requirements.txt
@@ -59,12 +60,12 @@ jobs:
           if [ "${{ matrix.kernel }}" = "latest" ]; then
             kernver="6.9-rc3"
           fi
-          python3 generate_encodings.py \
-            --kernver $kernver --commit $commit \
-            --kernbasedir "${{ github.workspace }}/linux" \
-            --outdir ../bpf-encodings/${{ matrix.kernel }} \
-            --specific-op ${{ matrix.insn }} || echo "WE FAILED!!!!!!!"
-          /home/runner/work/agni/agni/llvm-to-smt/llvm-passes/force_functions_early_exit.sh /home/runner/work/agni/agni/bpf-encodings/${{ matrix.kernel }}/BPF_AND/BPF_AND.Oz.ll /home/runner/work/agni/agni/bpf-encodings/${{ matrix.kernel }}/BPF_AND BPF_AND.Oz.ffee.ll
+          # python3 generate_encodings.py \
+            # --kernver $kernver --commit $commit \
+            # --kernbasedir "${{ github.workspace }}/linux" \
+            # --outdir ../bpf-encodings/${{ matrix.kernel }} \
+            # --specific-op ${{ matrix.insn }} || echo "WE FAILED!!!!!!!"
+          # /home/runner/work/agni/agni/llvm-to-smt/llvm-passes/force_functions_early_exit.sh /home/runner/work/agni/agni/bpf-encodings/${{ matrix.kernel }}/BPF_AND/BPF_AND.Oz.ll /home/runner/work/agni/agni/bpf-encodings/${{ matrix.kernel }}/BPF_AND BPF_AND.Oz.ffee.ll
       - name: Check
         run: |
           ls bpf-encodings/${{ matrix.kernel }}
